server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000
    accept-count: 2000
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/volvo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true&useServerPrepStmts=false&useCompression=true
    username: root
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.jdbc.Driver
    minimum-idle: 20
    idle-timeout: 180000
    maximum-pool-size: 50
    auto-commit: true
    pool-name: mainHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1
  mybatis:
    mapper-locations: classpath:mapper/*.xml
